[package]
name = "min-caml-rust"
version = "0.1.0"
authors = ["koba-e964 <koba_max@kobas-Air.pohe>"]

[dependencies]
nom = "^4"
ordered-float = "0.5"
lazy_static = "^1"

[profile.dev]
debug = false

[profile.test]
debug = false