[package]
name = "min-caml-rust"
version = "0.1.0"
authors = ["koba-e964 <koba_max@kobas-Air.pohe>"]

[dependencies]
nom = "^3.0"
ordered-float = "0.4"
lazy_static = "^0.2"

[profile.dev]
debug = false

[profile.test]
debug = false